/* Generated with cbindgen:0.29.0 */

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * A simple struct to test FFI
 */
typedef struct Point {
  double x;
  double y;
} Point;

/**
 * Add two numbers together
 */
int32_t add(int32_t a, int32_t b);

/**
 * Multiply two numbers
 */
int32_t multiply(int32_t a, int32_t b);

/**
 * Calculate distance between two points
 */
double distance(struct Point p1, struct Point p2);

/**
 * Free a string allocated by Rust
 */
void free_string(char *s);
